name: Update Ambrea Time API

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm init -y
          npm install node-fetch@2

      - name: Update time.json
        run: |
          node scripts/update-time.js

      - name: Commit & push
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git pull --rebase origin main || true
          git add public/time.json
          git commit -m "chore(time): update time.json [skip ci]" || true
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
