name: Update Ambrea Time API

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes (UTC)
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update-time.yml"

permissions:
  contents: write

jobs:
  update-time:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm init -y
          npm install node-fetch@2

      - name: Update time.json
        run: |
          mkdir -p scripts
          node scripts/update-time.js

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/time.json
          git commit -m "chore(time): update time.json [skip ci]" || exit 0
          git push
